### ISSUE TITLE
Ce qu'on doit faire

### ISSUE THREAD

**Issue by BloodyNightWolf** [KebeQ/TP2web#1]
On doit faire : 

- [L'authentification des clients (Assurer du fonctionnement)]
- [La modification du client]
- [Vérification et ré-écriture des validations pour le compte client.]
(Ajout d'un moyen de se connecter sans avoir besoin de créer un compte à chaque fois)

Il faut vraiment qu'on accélère le pas car on peut pas remettre un TP tellement défectueux.

**Comment by KebeQ** [comment]
Ouais je vais finir mon tp de bd pi après je me lance là-dessus
